export const SET_CENTER = 'mapActions/SET_CENTER';
export const SET_SEARCH_TERM = 'mapActions/SET_SEARCH_TERM';
export const SET_MAP_CLICK_LOCATION = 'mapActions/SET_MAP_CLICK_LOCATION';
export const SET_BOUNTY_STAKE_AMOUNT = 'mapActions/SET_BOUNTY_STAKE_AMOUNT';
export const SET_SELECTED_BOUNTY_TO_STAKE = 'mapActions/SET_SELECTED_BOUNTY_TO_STAKE';
export const TOGGLE_BOUNTY_STAKED_SUCCESSFULLY = 'mapActions/TOGGLE_BOUNTY_STAKED_SUCCESSFULLY';
export const TOGGLE_BOUNTY_SUBMISSION_SUCCESSFULLY = 'mapActions/TOGGLE_BOUNTY_SUBMISSION_SUCCESSFULLY';
export const SET_BOUNTY_FILTER = 'mapActions/SET_BOUNTY_FILTER';
