export const SET_IS_ANY_UNLOCKED_ACCOUNT = 'web3Actions/SET_IS_ANY_UNLOCKED_ACCOUNT';
export const SET_NETWORK_NAME = 'web3Actions/SET_NETWORK_NAME';
export const SET_NITROGEN_BALANCE = 'web3Actions/SET_NITROGEN_BALANCE';
